  app:
    - app/bulldog.js
    - app/todoTxt.js
    - app/models/**/*.js
    - app/collections/**/*.js
    - app/agents/**/*.js
    - app/views/**/*.js
    - app/routers/**/*.js
    - app/views/templates/*.mustache
