template_function: Mustache.template
template_extension: .mustache
gzip_assets: off

compress_assets: off

javascripts:

  lib:
    - lib/dev/jquery-1.7.1.js
    - lib/dev/underscore.js
    - lib/dev/underscore.string.js
    - lib/dev/backbone.js
    - lib/dev/backbone.localstorage.js
    - lib/dev/bootstrap.js
    - lib/mustache.js
    - lib/mustache-jammit.js
    - lib/add-underscore-string.js
  app:
    - app/bulldog.js
    - app/init.js
    - app/apis/**/*.js
    - app/models/**/*.js
    - app/collections/**/*.js
    - app/controllers/**/*.js
    - app/agents/**/*.js
    - app/views/**/*.js
    - app/routers/**/*.js
    - app/views/templates/*.mustache

