  lib:
    - lib/release/jquery-1.7.1.min.js
    - lib/release/underscore-min.js
    - lib/release/underscore.string-min.js
    - lib/release/bootstrap.min.js
    - lib/release/backbone-min.js
    - lib/release/backbone.localstorage-min.js
    - lib/mustache.js
    - lib/mustache-jammit.js
    - lib/add-underscore-string.js
