template_function: Mustache.template
template_extension: .mustache
gzip_assets: off
compress_assets: off

javascripts:

  all:
    - lib/release/jquery-1.7.1.min.js
    - lib/release/underscore-min.js
    - lib/release/underscore.string-min.js
    - lib/release/backbone-min.js
    - lib/release/backbone.localstorage-min.js
    - lib/release/bootstrap.min.js
    - lib/mustache.js
    - lib/mustache-jammit.js
    - lib/add-underscore-string.js
    - app/bulldog.js
    - app/todoTxt.js
    - app/models/**/*.js
    - app/collections/**/*.js
    - app/agents/**/*.js
    - app/views/**/*.js
    - app/routers/**/*.js
    - app/views/templates/*.mustache

stylesheets:

  all:
    - lib/release/bootstrap.min.css
    - build/dev/bulldog.css